# GET http://127.0.0.1:8000/fitzy/check/user/
# Content-Type: application/json
# Authorization:Token e3861844b1266c58c9896c3e7a93eacbb78348a0

# {
#     "username":"roo1t",
#     "password":"toor"
# }
# POST http://127.0.0.1:8000/fitzy/login/
# Content-Type: application/json

# {
#     "username":"root",
#     "password":"toor"
# }

PUT  http://127.0.0.1:8000/fitzy/change_password/1/
Content-Type: application/json
Authorization:Token e3861844b1266c58c9896c3e7a93eacbb78348a0

{
    "username":"mahesh",
    "old_password":"Mahesh@123",
    "password":"Root@1234",
    "password2":"Root@1234"
}